version: '3.8'

services:
  # Redis数据库（向量存储）
  redis:
    image: redis:latest
    container_name: "aitok_redis"
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "yes", "--requirepass", "123456789" ]
    volumes:
      - /opt/aitok-data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # Qdrant向量数据库
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aitok-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - /opt/aitok-data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # Milvus 依赖的 etcd 存储
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /opt/aitok-data/etcd:/etcd
    command: etcd -advertise-client-urls=http://192.168.80.131:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    ports:
      - "2379:2379"  # 暴露etcd端口供外部连接
    networks:
      - app-network
    restart: unless-stopped

  # MinIO 对象存储
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # 控制台端口
    volumes:
      - /opt/aitok-data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - app-network
    restart: unless-stopped

  # Milvus 向量数据库
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.3
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      # 使用VM的IP地址
      ETCD_ENDPOINTS: 192.168.80.131:2379
      MINIO_ADDRESS: 192.168.80.131:9000
    volumes:
      - /opt/aitok-data/milvus:/var/lib/milvus
    ports:
      - "19530:19530"  # Milvus gRPC端口
      - "9091:9091"    # Milvus管理端口
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - app-network
    restart: unless-stopped

  # Milvus 可视化管理工具
  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.3.3
    environment:
      MILVUS_URL: 192.168.80.131:19530
    ports:
      - "3000:3000"  # Attu Web界面端口
    depends_on:
      - "milvus"
    networks:
      - app-network
    restart: unless-stopped

  # Redis Commander - Redis可视化管理工具
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:123456789
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
